require 'PureMVC_Ruby'
module Notifications
	class Notifications
    #INFO NOTIFICATIONS
    LOG_INFO = "LOG_INFO"
    LOG_ERROR = "LOG_ERROR"
    
		UPDATE_SCREEN = "UPDATE_SCREEN" #Used to instruct the screen to refresh with some sort of message
		EXECUTE_EXTERNAL_COMMAND = "EXECUTE_EXTERNAL_COMMAND" #Used to instruct the execution of a command
		
    EXTERNAL_COMMAND_NOT_EXECUTED = "EXTERNAL_COMMAND_NOT_EXECUTED"
    
		EXTERNAL_COMMAND_EXECUTED = "EXTERNAL_COMMAND_EXECUTED" #Used to signal that a command has been executed
    EXTERNAL_COMMAND_FINISHED_EXECUTING = "EXTERNAL_COMMAND_FINISHED_EXECUTING" #Used to signal that a command has finished executing
    
    #Command Notifications
    EXIT_SUCCESS = "EXIT_SUCCESS"
    EXIT_FAILURE = "EXIT_FAILURE"
    
    #INPUT PARSING STATE COMMANDS
    VALIDATE_PROGRAM_ARGS = "VALIDATE_PROGRAM_ARGS"
    
    #DISCOVERY STATE COMMANDS
    RETRIEVE_MEDIA_FILES = "RETRIEVE_MEDIA_FILES"
    GENERATE_ENCODING_JOBS = "GENERATE_ENCODING_JOBS"
    
    #ENCODING CYCLE SUPER-STATE
    EXECUTE_ALL_ENCODING_JOBS = "EXECUTE_ALL_ENCODING_JOBS"
    
    #EXTRACTION STATE
    EXTRACT_TRACK = "EXTRACT_TRACK"
    
    #GENERATION STATE
    GENERATE_AVISYNTH_FILE = "GENERATE_AVISYNTH_FILE"
    
    #ENCODING STATE
    ENCODE_FILE = "ENCODE_FILE"
    
    #MULTIPLEX STATE
    MULTIPLEX_FILE = "MULTIPLEX_FILE"
    
    #CLEANUP STATE
    CLEANUP_FILES = "CLEANUP_FILES"
    
    #POST-ENCODING STATE
    EXECUTE_POST_ENCODING_COMMANDS = "EXECUTE_POST_ENCODING_COMMANDS"
	end
end